# web port
server:
  port: ${SERVER_PORT:8081}

# log config
logging:
  config: classpath:logback.xml
  path: ${DATA_PATH:.}/applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      #datax_admin部署地址，如调度中心集群部署存在多个地址则用逗号分隔，执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；
      addresses: http://${DATAX_ADMIN_HOST:127.0.0.1}:${DATAX_ADMIN_PORT:9527}
    executor:
      #执行器AppName，每个执行器机器集群的唯一标示,执行器心跳注册分组依据；
      appname: datax-executor
      #默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      #执行器Server端口号，默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: ${EXECUTOR_PORT:9999}
      ### job log path
      #执行器运行日志文件存储磁盘路径,需要对该路径拥有读写权限;
      logpath: ${DATA_PATH:.}/applogs/executor/jobhandler
      ### job log retention days
      # 执行器日志文件保存天数,过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    #datax json临时文件保存路径
    jsonpath: ${JSON_PATH:.}
    pythonpath: python

# DataX启动脚本地址，例如：xxx/datax/bin/datax.py 如果系统配置DataX环境变量（DATAX_HOME），logpath、jsonpath、pypath可不配，log文件和临时json存放在环境变量路径下
  pypath: ${PYTHON_PATH:C:\datax\bin\datax.py}